export const styles = [
  {
    label: "Aestheticism",
    value: "Aestheticism",
    role: "A",
  },
  {
    label: "Art Brut",
    value: "Art Brut",
    role: "A",
  },
  {
    label: "Action painting",
    value: "Action painting",
    role: "A",
  },
  {
    label: "American realism",
    value: "American realism",
    role: "A",
  },
  {
    label: "American Scene Painting",
    value: "American Scene Painting",
    role: "A",
  },
  {
    label: "Ancient",
    value: "Ancient",
    role: "A",
  },
  {
    label: "Art Deco",
    value: "Art Deco",
    role: "A",
  },
  {
    label: "Art Informel",
    value: "Art Informel",
    role: "A",
  },
  {
    label: "Art Nouveau",
    value: "Art Nouveau",
    role: "A",
  },
  {
    label: "Arte Povera",
    value: "Arte Povera",
    role: "A",
  },
  {
    label: "Art Soviet",
    value: "Art Soviet",
    role: "A",
  },
  {
    label: "Avant-garde",
    value: "Avant-garde",
    role: "A",
  },
  {
    label: "Barbizon school",
    value: "Barbizon school",
    role: "B",
  },
  {
    label: "Baroque",
    value: "Baroque",
    role: "B",
  },
  {
    label: "Ancient",
    value: "Ancient",
    role: "B",
  },
  {
    label: "Ancient",
    value: "Ancient",
    role: "B",
  },
  {
    label: "Ancient",
    value: "Ancient",
    role: "B",
  },
  {
    label: "Ancient",
    value: "Ancient",
    role: "B",
  },
  {
    label: "Ancient",
    value: "Ancient",
    role: "B",
  },
];

// const rest = {
//   b: [
//     "Barbizon school",
//     "Baroque",
//     "Bauhaus",
//     "Berlin Secession",
//     "Black Arts Movement",
//     "Bengal",
//     "Byzantine",
//     "Brutalism",
//   ],
//   c: [
//     "Classical Realism",
//     "Cloisonnism",
//     "COBRA",
//     "Color Field",
//     "Computer art",
//     "Conceptual art",
//     "Constructivism",
//     "Cubo-Futurism",
//     "Cubism",
//     "Cynical realism",
//   ],
//   d: [
//     "Dada",
//     "Dadaism",
//     "Danube school",
//     "Dau-al-Set",
//     "De Stijl ",
//     "Deconstructivism",
//     "Digital art",
//   ],
//   e: [
//     "Ecological Art",
//     "Egyptian",
//     "Environmental art",
//     "Excessivism",
//     "Expressionism",
//   ],
//   f: [
//     "Fantastic realism",
//     "Fauvism",
//     "Feminist art",
//     "Figurative art",
//     "Figuration Libre",
//     "Folk art",
//     "Fluxus",
//     "Funk art",
//     "Futurism",
//   ],
//   g: ["Geometric abstract art", "Greek", "Graffiti", "Gutai group", "Gothic"],
//   h: [
//     "Happening",
//     "Harlem Renaissance",
//     "Heidelberg School",
//     "Hudson River School",
//     "Hurufiyya",
//     "Hypermodernism",
//     "Hyperrealism",
//   ],
//   i: [
//     "Imaginism",
//     "Impressionism",
//     "Incoherents",
//     "Interactive Art",
//     "Institutional critique",
//     "International Gothic",
//     "International Typographic Style",
//   ],
//   k: ["Kinetic art", "Kinetic Pointillism", "Kitsch movement"],
//   l: [
//     "Land art",
//     "Les Nabis",
//     "Letterism",
//     "Light and Space",
//     "Lowbrow",
//     "Lyco art",
//     "Lyrical abstraction",
//   ],
//   m: [
//     "Magic realism",
//     "Mail art",
//     "Mannerism",
//     "Massurrealism",
//     "Maximalism",
//     "Metaphysical painting",
//     "Medieval",
//     "Mingei",
//     "Minimalism",
//     "Modernism",
//     "Modular constructivism",
//   ],
//   n: [
//     "Naive art",
//     "Nadaism",
//     "Neoclassicism",
//     "Neo-Dada",
//     "Neo-expressionism",
//     "Neo-Fauvism",
//     "Neo-figurative",
//     "Neogeo ",
//     "Neoism",
//     "Neo-primitivism",
//     "Neo-romanticism",
//     "Net art",
//     "New Objectivity",
//     "New Sculpture",
//     "Northwest School",
//     "Nuclear art",
//   ],
//   o: ["Objective abstraction", "Op Art", "Orphism"],
//   p: [
//     "Photorealism",
//     "Panfuturism",
//     "Pixel art",
//     "Plasticien",
//     "Plein Air",
//     "Pointillism",
//     "Pop art",
//     "Post-impressionism",
//     "Postminimalism",
//     "Precisionism",
//     "Pre-Raphaelitism",
//     "Primitivism",
//     "Private Press",
//     "Process art",
//     "Psychedelic art",
//     "Purism",
//   ],
//   q: ["Qajar art", "Quito School"],
//   r: [
//     "Rasquache",
//     "Rayonism",
//     "Realism",
//     "Regionalism",
//     "Remodernism",
//     "Renaissance",
//     "Retrofuturism",
//     "Rococo",
//     "Romanesque",
//     "Romanticism",
//   ],
//   s: [
//     "Samikshavad",
//     "Serial art",
//     "Shin hanga",
//     "Shock art",
//     "Sōsaku hanga",
//     "Socialist realism",
//     "Sots art",
//     "Space art",
//     "Street art",
//     "Stuckism",
//     "Sumatraism",
//     "Superflat",
//     "Suprematism",
//     "Surrealism",
//     "Symbolism",
//     "Synchromism",
//     "Synthetism",
//   ],
//   t: ["Tachisme ", "Toyism", "Transgressive art", "Tonalism"],
//   u: ["Ukiyo-e", "Unilalianism"],
//   v: [
//     "Vancouver School",
//     "Vanitas",
//     "Verdadism",
//     "Video art",
//     "Visual Art",
//     "Viennese Actionism",
//     "Vorticism",
//   ],
//   y: ["Yoruba"],
// };
