export const colors = {
  black: [
    "authoritarian",
    "power",
    "strength",
    "evil",
    "inteligent",
    "deadly",
    "barren",
  ],
  white: ["pure", "innocent", "clean", "spaceful", "neutral"],
  gray: ["neutral", "timeless", "practical"],
  red: [
    "love",
    "romance",
    "gentle",
    "comfort",
    "energetic",
    "exciteted",
    "intense",
    "life",
    "blood",
  ],
  orange: [
    "happiness",
    "energy",
    "excitement",
    "enthusiasm",
    "warmth",
    "wealth",
    "prosperity",
    "sopisticcation",
    "changed",
    "stimulation",
  ],
  yellow: [
    "happiness",
    "smiling",
    "laughting",
    "cheery",
    "warmth",
    "optimism",
    "hunger",
    "intensity",
    "frustration",
    "anger",
    "attentive",
  ],
  greeen: [
    "natural",
    "cool",
    "growing",
    "wealthy",
    "healthy",
    "envy",
    "tranquility",
    "harmony",
    "calmness",
    "fertility",
  ],
  blue: [
    "calmness",
    "serenity",
    "cold",
    "uncaring",
    "careless",
    "loyality",
    "trully",
  ],
  brown: [
    "reliable",
    "stable",
    "friendly",
    "sad",
    "warmth",
    "comfort",
    "secure",
    "natural",
    "organic",
  ],
  pink: ["gentle", "agitation"],
  purple: [
    "royal",
    "wise",
    "exotic",
    "spiritual",
    "prosperity",
    "respect",
    "mysterious",
  ],
};
